// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoljdvksctxlkpofkljw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbGpkdmtzY3R4bGtwb2ZrbGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDUyMDYsImV4cCI6MjA2ODQyMTIwNn0.vuwo8MgjfwzlF8XyIwwHNvj62a-luB2IVNS_OYcktEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});